### ISSUE TITLE
Elmocut crashes seconds after opening

### ISSUE THREAD

**Issue by Tornadoalley** [elmoiv/elmocut#74]
**Describe the bug**
The application when opened shows the main screen and a prompt at the bottom stating: "Arping your network..." 
After about 5-10 seconds the window disappears and the Task Manager shows the application has crashed. No error message is displayed during this. I have tried both the SFX and regular install but both cause this issue. Only other application running is Firefox

**To Reproduce**
1. Open elmoCUT.exe
2. Wait 10 seconds
3. The application will crash

**Expected behavior**
Application does not crash

**Screenshots**

https://github.com/elmoiv/elmocut/assets/73433060/ffea1a96-42a7-4223-9b03-f450d5ee25ba

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro Build 22631
 - Browser: Firefox
 - Version: v1.0.7 x64 **and SFX**

**Additional context**

**Comment by elmoiv** [comment]
Have you tried to run it as admin?

**Comment by RedstoneKopf** [comment]
I have the same problem with Windows 11 Pro Build 22631.3593 and all virus prot disabled.
And yes, it also has this problem if i run it as admin

**Comment by elmoiv** [comment]
What version of npcap had you installed?

**Comment by Balaarizalu** [comment]
Hello, I want to report an error using ElmoCut 1.0.7.x64 :

Traceback (most recent call last):
  File "elmoCut.py", line 26, in <module>
  File "tools\utils_gui.py", line 28, in duplicate_elmocut
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by elmoiv** [comment]
@Balaarizalu 
Try this one:
https://github.com/elmoiv/elmocut/issues/70#issuecomment-1876229323

**Comment by smiffy0411** [comment]
hiya, im also having this error, even when running as admin, im also using windows 11 pro.

**Comment by elmoiv** [comment]
> hiya, im also having this error, even when running as admin, im also using windows 11 pro.

https://github.com/elmoiv/elmocut/issues/70#issuecomment-1876229323
