### ISSUE TITLE
While opening elmocut after the install

### ISSUE THREAD

**Issue by Rayzerx1** [elmoiv/elmocut#75]
Traceback (most recent call last):
  File "elmoCut.py", line 2, in <module>
ImportError: DLL load failed: The specified module could not be found.

**Comment by Xpower7** [comment]
I have the same issue. Windows 11.

**Comment by Xpower7** [comment]
> Traceback (most recent call last): File "elmoCut.py", line 2, in ImportError: DLL load failed: The specified module could not be found.

I have the same issue. Windows 11.

EDIT 2
You need to install Microsoft C++ 2022 Redist.
